# Generated by Django 2.1.3 on 2018-11-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_room',
            field=models.CharField(default='lobby', max_length=256),
            preserve_default=False,
        ),
    ]
